name: push to server
on:
    release
jobs:
    deploy:
        runs-on:
            - linux
        steps:
            - name: Code Checkout
              uses: actions/checkout@v2
            - name: Genrate ENV
              run: |
                echo "OPENAI_KEY=${{secrets.OPENAI_KEY}}" >> .env 
            - name: Install dependency
              run: |
                python -m pip install --upgrade pip
                pip install -r reqs.txt
            - name: start API and UI and test
              run: |
                chmod +x run.sh
                ./run.sh
