name: continous devlopment
on:
    push:
        branches: [master]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v2

            - name: Set up python enviroment
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'
            - name: Install dependency
              run: |
                python -m pip install --upgrade pip
                pip install -r reqs.txt
            - name: run test
              run: |
                pytest
            - name: start API and UI
              run: |
                run.sh & sleep 10 & exit
            